spring.application.name=helpdesk
server.port=${SERVER_PORT:4200}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/helpdesk}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:helpdesk}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:helpdesk}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true
spring.flyway.validate-on-migrate=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
