services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helpdesk-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend/helpdesk
      dockerfile: Dockerfile
    container_name: helpdesk-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 4200
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/helpdesk
      SPRING_DATASOURCE_USERNAME: helpdesk
      SPRING_DATASOURCE_PASSWORD: helpdesk
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "4200:4200"

  postgres:
    image: postgres:17-alpine
    container_name: helpdesk-postgres
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helpdesk -d helpdesk"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
